ersion: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building Angular project..."
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
    